name       : dconf-editor
version    : 3.26.2
release    : 19
source     :
    - https://download.gnome.org/sources/dconf-editor/3.26/dconf-editor-3.26.2.tar.xz : 28b453fe49c49d7dfaf07c85c01d7495913f93ab64a0b223c117eb17d1cb8ad1
license    : GPL-2.0
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
