name       : dconf-editor
version    : 3.26.1
release    : 18
source     :
    - https://download.gnome.org/sources/dconf-editor/3.26/dconf-editor-3.26.1.tar.xz : 49332042a4c9a46ad6345055bb098c8701cbca7bc39ec9a9fd6e49b87ef1ea29
license    : GPL-2.0
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(glib-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxml-2.0)
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
