name       : dconf-editor
version    : 3.34.4
release    : 24
source     :
    - https://download.gnome.org/sources/dconf-editor/3.34/dconf-editor-3.34.4.tar.xz : de5b2a30e0d6d4fb72a0d3e98b1b95aa2acdab62e59a9f1391d96eeee9142a89
license    : GPL-2.0
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
