name       : dconf-editor
version    : 3.38.2
release    : 27
source     :
    - https://download.gnome.org/sources/dconf-editor/3.38/dconf-editor-3.38.2.tar.xz : 1253dad87e6213fbf313ff9ec9dc4358aa1b10261f28072c1dc0e0997b92f835
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
