name       : dconf-editor
version    : 3.38.3
release    : 28
source     :
    - https://download.gnome.org/sources/dconf-editor/3.38/dconf-editor-3.38.3.tar.xz : 571af4c7dad4f049b53e6cd728b79addf08c27ddab6bc57b396d211866ee79e3
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
