name       : dconf-editor
version    : 3.32.0
release    : 21
source     :
    - https://download.gnome.org/sources/dconf-editor/3.32/dconf-editor-3.32.0.tar.xz : f19d1332ac27e23ef3dc2ed07ba4e4646d9d7f05e2e78748aa525a1320adbaba
license    : GPL-2.0
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
