name       : dconf-editor
version    : 3.36.4
release    : 26
source     :
    - https://download.gnome.org/sources/dconf-editor/3.36/dconf-editor-3.36.4.tar.xz : 3ec309bbc920b15c2a5683e1a4962abf6911a8762c8a113c4d794f7e0ea53e79
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
