name       : dconf-editor
version    : 3.18.1
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/dconf-editor/3.18/dconf-editor-3.18.1.tar.xz : 35c17852acc7dc9015d35148c1c4ebec1477c252f1d979cb324e1e6010d1db13
license    : GPL-2.0
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(glib-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxml-2.0)
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
