name       : dconf-editor
version    : 3.36.2
release    : 25
source     :
    - https://download.gnome.org/sources/dconf-editor/3.36/dconf-editor-3.36.2.tar.xz : edcec8867f018589125f177407760c642bbbb52fe5122daac5905223d6b3e1c7
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
