name       : dconf-editor
version    : 3.34.3
release    : 23
source     :
    - https://download.gnome.org/sources/dconf-editor/3.34/dconf-editor-3.34.3.tar.xz : 9b491a6a9f3eecf6960b33d3992112d6adbc535fb04af50bcb6ab9a29b64028b
license    : GPL-2.0
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
