name       : dconf-editor
version    : 3.28.0
release    : 20
source     :
    - https://download.gnome.org/sources/dconf-editor/3.28/dconf-editor-3.28.0.tar.xz : 455b53d827820efd28a176ee52e13eda5cda8cdf4e31e0145cfdd69931bf0c5a
license    : GPL-2.0
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
