name       : dconf-editor
version    : 3.34.2
release    : 22
source     :
    - https://download.gnome.org/sources/dconf-editor/3.34/dconf-editor-3.34.2.tar.xz : cecc2a5cb44af68be80e970e83fb9e3e92e2a74df7c90b63324e6da19a929d5f
license    : GPL-2.0
component  : desktop.gnome
summary    : DConf Graphical Editor
description: |
    DConf Graphical Editor
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
